name: Bug Report
description: Report a bug in seqpacker
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal code to reproduce the issue.
      render: python

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - seqpacker version:
        - Python version:
        - OS:
      render: text
    validations:
      required: true
